tsapi_core:
    resource: "@TSAPICoreBundle/Controller/"
    type:     annotation
    prefix:   /

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_security_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
